<?php

/**
 * @file pdnuserrole.module
 */


/**
 * Implements hook_user_presave()
 *  Assign the role to new user which is based on the corresponding domain.com
 */

function pdnuserrole_user_presave(&$edit, $account, $category){
	// check if user is new.
     if (isset($account->is_new) && !empty($account->is_new)) {
        // extract the domain name from $eidt['mail']
        if(!empty($edit['mail'])){
         list($username, $domain) = explode("@", $edit['mail'], 2);
         $assign_role = array();
         if(strtolower($domain) == 'pdn.com' || strtolower($domain) == 'pearson.com'){
             // Get all roles exclude anonymous role.
            //$assign_role = user_roles(TRUE);
           // $account->roles[6] = TRUE;
             $edit['roles'] = array(19 => 'pearson employee'); // rid => role_name
         }
         // watchdog('pdn_autoassignrole', 'roles: %roles', array('%roles' => print_r($account->roles, true)));
        }
    }
}
